detect-client-opacity = true;
backend = "glx";
vsync = false;
glx-use-copysubbuffer-mesa = true;
glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;
unredir-if-possible = true;
unredir-if-possible-exclude = [
	"class_g = 'looking-glass-client' && !focused"
] 
shadow = false;
fading = false;
frame-opacity = 1.0;

