picom  &
autotiling & 
~/.config/polybar/launch_polybar.sh &
dunst &
parcellite &
feh --recursive --bg-fill --randomize /usr/share/wallpapers/yellow/* &
setxkbmap -layout de,ua -option grp:alt_shift_toggle &
xrdb ~/.Xresources &

exec i3
