[colors]
base = #dfd1a2 
pesto = #706f2d
text = #14233a
ochre = #aa7c07
blue = #c3c5d3
red = #fc4649
green = #44702d
transparent = #FF00000

[colors]
background = ${colors.base}
background-alt = ${colors.blue}
foreground = ${colors.text}
primary = ${colors.green}
secondary = ${colors.pesto}
alert = ${colors.red}
disabled = ${colors.ochre}

[bar/toph]
monitor = ${env:MONITOR:}
width = 70%
offset-x = 15%
offset-y = 2pt
height = 24pt
radius = 3

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

bottom = true

#border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin = 1	

font-0 = "Monofur Nerd Font Propo:size=18;2"


modules-left = xworkspaces
modules-center = applauncher 
modules-right = systray pulseaudio wlan date logout

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/applauncher]
type = custom/text
format = 
label-active-font = 1
format-foreground = ${colors.primary} 
click-left = "rofi -show drun"

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.primary}
label-active-foreground = ${colors.background}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%

label-muted =  
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

ramp-volume-foreground = ${colors.primary}

click-right = pavucontrol


[network-base]
type = internal/network
interval = 5
format-connected = <ramp-signal> <label-connected>
format-disconnected = <label-disconnected>

label-connected = %essid%
label-connected-foreground = ${colors.foreground}

label-disconnected = 󰤮
label-disconnected-foreground = ${colors.disabled}

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

ramp-signal-foreground = ${colors.primary}

[module/wlan]
inherit = network-base
interface-type = wireless

[module/wired-network]
type = internal/network
interface = eth1

[module/date]
type = internal/date
interval = 1.0

time = %H:%M
date-alt = %Y/%m/%d
label = %date% %time%
label-foreground = ${colors.primary}

[module/logout]
type = custom/text
format = 

format-background = ${colors.primary}
format-foreground = ${colors.background}

label-active-font = 1
 
click-left = "rofi -show power-menu -modi power-menu:rofi-power-menu -theme .config/rofi/themes/hw-light.rasi"

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
